package validate

const (
	// REQUIRED code
	REQUIRED = "REQUIRED"
	// INVALID code
	INVALID = "INVALID"
	// MAXLIMIT code
	MAXLIMIT = "MAX_LIMIT"
	// MINLIMIT code
	MINLIMIT = "MIN_LIMIT"
	// INVALIDEMAIL code
	INVALIDEMAIL = "INVALID_EMAIL"
	// INVALIDPASSWORD code
	INVALIDPASSWORD = "INVALID_PASSWORD"
	// EMAILEXISTS code
	EMAILEXISTS = "EMAIL_EXISTS"
	// PERMISSIONDENIED code
	PERMISSIONDENIED = "PERMISSION_DENIED"
	// CARNOTAVAILABLE code
	CARNOTAVAILABLE = "CAR_NOT_AVAILABLE"
	// NOTALLOWED code
	NOTALLOWED = "NOT_ALLOWED"
)
